# Generated by Django 3.2.8 on 2021-11-19 21:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signame', models.CharField(max_length=100)),
                ('sigdesc', models.TextField()),
                ('sigdomain', models.CharField(max_length=100)),
                ('numbers', models.IntegerField()),
                ('mentor', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None)),
                ('date', models.DateField()),
            ],
        ),
    ]
