# Generated by Django 3.2.8 on 2021-11-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursecontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('links', models.URLField()),
            ],
        ),
    ]
