# Generated by Django 3.2.8 on 2021-11-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIG', '0002_coursecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='belongs',
            field=models.IntegerField(default=0),
        ),
    ]
