# Generated by Django 3.2.8 on 2021-11-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIG', '0003_coursecontent_belongs'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.TextField()),
                ('sigid', models.IntegerField()),
                ('by', models.CharField(max_length=100)),
            ],
        ),
    ]
