# Generated by Django 3.2.8 on 2021-11-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIG', '0005_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='sigid',
            field=models.IntegerField(default=0),
        ),
    ]
